---
# This playbook deploys a simple standalone Tomcat 7 server. 

- hosts: localhost 
  remote_user: root

  tasks:
    - shell: echo "Hello World"
    
- name:Install java
  apt: name=nginx state=latest default_release=squeeze-backports update_cache=yes
    
